### ISSUE TITLE
访问频率受限

### ISSUE THREAD

**Issue by lqzhgood** [Zeroto521/Wox.Plugin.Youdao#2]
![image](https://user-images.githubusercontent.com/9134671/78215443-17e0d000-74ea-11ea-8e1b-5d80a3370476.png)

感觉还是 Api 的问题。 
还是开放一个私有key输入吧~~
稳当。也就麻烦一次

**Comment by Zeroto521** [comment]
个人是轻度使用~只要我手速够快，youdao 就跟不上我~。

可以考虑

- 普通用户 ->  `demo` 页面接口
- 高级用户 -> 个人申请 api

**Comment by lqzhgood** [comment]
我申请了 Api 不知道往哪填~
看了下代码 （不懂Python）  好像接口是直接写的  demo.youdao.com 这样是不是我有 自己的 Api key 也没法用？

**Comment by Zeroto521** [comment]
这倒有款私 key 版的 [youdao](http://www.wox.one/plugin/151)

**Comment by lqzhgood** [comment]
哎~ 那个复制有bug issues 也关了。
算了 将就用吧
